const express = require('express')
const session = require('express-session')
require('express-group-routes')
const app = express()
const router = express.Router()
const ejsLint = require('ejs-lint')
const cookieParser = require('cookie-parser')
const Body_parser = require('body-parser')
require('./Apps/kernal')(app, express, Body_parser, session)
app.use(cookieParser('123@123@!T'))
require('./Router/web')(app)
module.exports = app