const express = require('express')
const router = express.Router()
const StaffController = require('../Apps/Controllers/Staff.controller')

router.route('/')
    .get(StaffController.Page_Index)
    .get(StaffController.Staff_Profile)
router.route('/profile')
    .get(StaffController.Staff_Profile)
router.route('/Faculty')
    .get(StaffController.Faculty_Page)
router.route('/Faculty/Create')
    .get(StaffController.Get_Create_Faculty)
    .post(StaffController.Post_Create_Faculty)
router.route('/Faculty/:faculty_id')
    .get(StaffController.Get_Update_Faculty)
    .post(StaffController.Post_Upload_Faculty)
    .get(StaffController.Delete_Faculty)
router.route('/Faculty/Delete/:faculty_id')
    .get(StaffController.Delete_Faculty)
router.route('/Faculty/:faculty_id/Subject')
    .get(StaffController.Subject_Page)
router.route('/Faculty/:faculty_id/Subject/Create')
    .get(StaffController.Get_Create_Subject)
    .post(StaffController.Post_Create_Subject)
router.route('/Faculty/:faculty_id/Subject/:subject_id')
    .get(StaffController.Get_Update_Subject)
router.route('/Faculty/:faculty_id/Subject/:subject_id/Delete')
    .get(StaffController.Get_Delete_Subject)
router.route('/Faculty/Subject/:subject_id/Class')
    .get(StaffController.Class_Page)
router.route('/Faculty/Subject/:subject_id/Class/Create')
    .get(StaffController.Get_Create_Class)
    .post(StaffController.Post_Create_Class)
router.route('/Faculty/Subject/:subject_id/Class/:class_id/Update')
    .get(StaffController.Get_Update_Class)
    .post(StaffController.Post_Update_Class)
router.route('/Faculty/Subject/:subject_id/Class/:class_id/Delete')
    .get(StaffController.Get_Delete_Class)
router.route('/Faculty/Subject/:subject_id/Class/:class_id/Detail')
    .get(StaffController.Get_Class_Detail)
router.route('/Faculty/Subject/:subject_id/Class/:class_id/Exercise')
    .get(StaffController.Get_Exercise)
router.route('/Account')
    .get(StaffController.Index_Account)
router.route('/Account/:role_id')
    .get(StaffController.List_Account)
module.exports = router
