const router = require('express').Router()
const HomeController = require('../Apps/Controllers/Home.controller')
const StaffController = require('../Apps/Controllers/Staff.controller')
const auth = require('../Apps/midderware/au.midderware')

router.get('/', HomeController.Home_Page)
router.get('/login', HomeController.GetLogin)
router.post('/login', HomeController.PostLogin)
router.get('/logout', HomeController.LogOut)
router.get('/staff',auth.reqAuth, auth.CheckRole, StaffController.Page_Index)
router.get('/staff/:staff_id',auth.reqAuth, auth.CheckRole, StaffController.Staff_Profile)
router.get('/subject/:faculty_id', auth.reqAuth, auth.CheckRole, StaffController.Subject_Page)
router.get('/Faculty/subject/class/:subject_id', auth.reqAuth, auth.CheckRole, StaffController.Class_Page)
router.get('/Faculty',auth.reqAuth, auth.CheckRole, StaffController.Faculty_Page)
router.get('/class', StaffController.Class_Page)
router.get('/subject', StaffController.Subject_Page)
module.exports = router
