const router = require('express').Router()
const HomeController = require('../Apps/Controllers/Home.controller')
const StaffController = require('../Apps/Controllers/Staff.controller')
const StudentAndTutorController = require('../Apps/Controllers/StudentAndTutor.controller')
const auth = require('../Apps/midderware/au.midderware')

router.get('/', HomeController.Home_Page)
router.get('/login', HomeController.GetLogin)
router.post('/login', HomeController.PostLogin)
router.get('/logout', HomeController.LogOut)
router.get('/staff',auth.reqAuth, auth.CheckStaff, StaffController.Page_Index)
router.get('/staff/profile',auth.reqAuth, auth.CheckStaff, StaffController.Staff_Profile)
router.get('/Faculty/Create', auth.reqAuth, auth.CheckStaff, StaffController.Get_Create_Faculty)
router.post('/Faculty/Create', auth.reqAuth, auth.CheckStaff, StaffController.Post_Create_Faculty)
router.get('/Faculty/Update/:faculty_id', auth.reqAuth, auth.CheckStaff, StaffController.Get_Update_Faculty)
router.get('/Faculty/Delete/:faculty_id', auth.reqAuth, auth.CheckStaff, StaffController.Delete_Faculty)
router.get('/Faculty/Subject/:faculty_id', auth.reqAuth, auth.CheckStaff, StaffController.Subject_Page)
router.get('/Faculty/Subject/:faculty_id/Create', auth.reqAuth, auth.CheckStaff, StaffController.Get_Create_Subject)
router.post('/Faculty/Subject/:faculty_id/Create', auth.reqAuth, auth.CheckStaff, StaffController.Post_Create_Subject)
router.get('/Subject/Update/:subject_id', auth.reqAuth, auth.CheckStaff, StaffController.Get_Update_Subject)
router.get('/Subject/Delete/:subject_id', auth.reqAuth, auth.CheckStaff, StaffController.Get_Update_Subject)
router.get('/Faculty/subject/class/:subject_id', auth.reqAuth, auth.CheckStaff, StaffController.Class_Page)
router.get('/Faculty',auth.reqAuth, auth.CheckStaff, StaffController.Faculty_Page)
router.get('/class', StaffController.Class_Page)
router.get('/subject', StaffController.Subject_Page)
router.get('/', HomeController.Home_Page)
router.get('/student',auth.reqAuth ,StudentAndTutorController.Class_Page)
router.get('/student/detail',auth.reqAuth ,StudentAndTutorController.Profile_Page)
router.get('/ForgotPassword', HomeController.Get_Forgot_Password)
router.post('/ForgotPassword', HomeController.Post_Forgot_Password)
// module.exports = (app) =>{
//     app.group('/', (router)=>{
//         router.get('/', HomeController.Home_Page)
//         router.get('/login', HomeController.GetLogin)
//         router.post('/login', HomeController.PostLogin)
//         router.get('/ForgotPassword', HomeController.Get_Forgot_Password)
//         router.post('/ForgotPassword', HomeController.Post_Forgot_Password)
//         router.use((req, res, next)=>{
//             auth.reqAuth(req, res, next)
//         })
//         router.get('/logout', HomeController.LogOut)
//     })
//     app.group('/staff', (router)=>{
//         router.use((req, res, next)=>{
//             auth.reqAuth(req, res, next)
//         })
//         router.use((req, res, next)=>{
//             auth.CheckStaff(req, res, next)
//         })
//         router.get('/', StaffController.Page_Index)
//         router.get('/profile', StaffController.Staff_Profile)
//         router.get('/Faculty', StaffController.Faculty_Page)
//         router.get('/Faculty/Create', StaffController.Get_Create_Faculty)
//         router.post('/Faculty/Create', StaffController.Post_Create_Faculty)
//         router.get('/Faculty/Update/:faculty_id', StaffController.Get_Update_Faculty)
//         router.post('/Faculty/Update/:faculty_id', StaffController.Post_Upload_Faculty)
//         router.get('/Faculty/Subject/:faculty_id', StaffController.Subject_Page)
//         router.get('/Faculty/Subject/:faculty_id/Create', StaffController.Get_Create_Subject)
//         router.post('/Faculty/Subject/:faculty_id/Create', StaffController.Post_Create_Subject)
//     })
// }
module.exports = router

